name: test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "20.9.0"

      - name: Install Dependencies
        run: npm install

      - name: Check JWT Secret
        run: echo "JWT Secret is $JWT_ACCESS_SECRET"
        env:
          JWT_ACCESS_SECRET: ${{ secrets.JWT_ACCESS_SECRET }}

      - name: Run Tests
        run: npm test
        env:
          JWT_ACCESS_SECRET: ${{ secrets.JWT_ACCESS_SECRET }}
        continue-on-error: true

      - name: Close PR on Failure
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(echo ${{ github.event.pull_request.number }})
          curl -X PATCH -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER -d '{"state":"closed"}'
