name: test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "20.9.0"

      - name: Install Dependencies
        run: npm install

      - name: Check JWT Secret
        run: echo "JWT Secret is $JWT_SECRET"
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Run Tests
        run: npm test
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
